apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  labels:
    app: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - name: petstore
        image: petstore
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 250m
            memory: 8Mi
          limits:
            cpu: 500m
            memory: 16Mi
        livenessProbe:
          httpGet:
            path: /api/pets
            port: http
          initialDelaySeconds: 1
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/pets
            port: http
          initialDelaySeconds: 1
          periodSeconds: 1
